### ISSUE TITLE
 No module named 'igl.pyigl'

### ISSUE THREAD

**Issue by throb081** [tyhuang0428/DreamControl#1]
Traceback (most recent call last):
  File "G:\PaperCode\DreamControl\DreamControl-main\launch.py", line 302, in <module>
    main(args, extras)
  File "G:\PaperCode\DreamControl\DreamControl-main\launch.py", line 136, in main
    import threestudio
  File "G:\PaperCode\DreamControl\DreamControl-main\threestudio\__init__.py", line 55, in <module>
    from . import data, models, systems
  File "G:\PaperCode\DreamControl\DreamControl-main\threestudio\data\__init__.py", line 1, in <module>
    from . import co3d, image, multiview, uncond
  File "G:\PaperCode\DreamControl\DreamControl-main\threestudio\data\co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "G:\PaperCode\DreamControl\DreamControl-main\threestudio\data\uncond.py", line 17, in <module>
    from threestudio.utils.ops import (
  File "G:\PaperCode\DreamControl\DreamControl-main\threestudio\utils\ops.py", line 9, in <module>
    from igl import fast_winding_number, point_mesh_squared_distance, read_obj
  File "C:\ProgramData\Anaconda3\envs\DreamControl\Lib\site-packages\igl\__init__.py", line 8, in <module>
    from .pyigl import *
ModuleNotFoundError: No module named 'igl.pyigl'

你好，我在调试的时候发现ModuleNotFoundError: No module named 'igl.pyigl'
这个bug，然后我仔细看了一下，主要是
from igl import fast_winding_number_for_meshes, point_mesh_squared_distance, read_obj
这个语句报错，我去查了一下libigl2.5.0版本没有fast_winding_number_for_meshes这个类，所以想问一下你你的libigl是什么版本，以及Python版本。我的Python版本为3.12

**Comment by tyhuang0428** [comment]
你好，谢谢关注我们的工作。
我的python版本是3.10，igl版本是2.4.1，也许你可以试试看。
不过我并没有在windows上验证过我的代码，你也可以参考threestudio里和windows相关的issue ([link](https://github.com/threestudio-project/threestudio/issues))

**Comment by throb081** [comment]
感谢您的回复！！！对我帮助很大。我在Linux上成功运行了您的代码，并且生成的图片的效果真的很棒。然而我发现在changlog中提到可以将模型导出成obj文件，但是在生成的结果好像没有发现，想问一下如果想导出的结果为obj，需要进行一些什么设置呢

**Comment by tyhuang0428** [comment]
> 感谢您的回复！！！对我帮助很大。我在Linux上成功运行了您的代码，并且生成的图片的效果真的很棒。然而我发现在changlog中提到可以将模型导出成obj文件，但是在生成的结果好像没有发现，想问一下如果想导出的结果为obj，需要进行一些什么设置呢

你可以试试下面的指令，“path/to/trial/dir”是你训练中log文件夹路径，找到相应位置的parsed.yaml和last.ckpt改进去应该就可以导出obj了
```sh
# this uses default mesh-exporter configurations which exports obj+mtl
python launch.py --config path/to/trial/dir/configs/parsed.yaml --export --gpu 0 resume=path/to/trial/dir/ckpts/last.ckpt system.exporter_type=mesh-exporter
# specify system.exporter.fmt=obj to get obj with vertex colors
# you may also add system.exporter.save_uv=false to accelerate the process, suitable for a quick peek of the result
python launch.py --config path/to/trial/dir/configs/parsed.yaml --export --gpu 0 resume=path/to/trial/dir/ckpts/last.ckpt system.exporter_type=mesh-exporter system.exporter.fmt=obj
# for NeRF-based methods (DreamFusion, Magic3D coarse, Latent-NeRF, SJC)
# you may need to adjust the isosurface threshold (25 by default) to get satisfying outputs
# decrease the threshold if the extracted model is incomplete, increase if it is extruded
python launch.py --config path/to/trial/dir/configs/parsed.yaml --export --gpu 0 resume=path/to/trial/dir/ckpts/last.ckpt system.exporter_type=mesh-exporter system.geometry.isosurface_threshold=10.
# use marching cubes of higher resolutions to get more detailed models
python launch.py --config path/to/trial/dir/configs/parsed.yaml --export --gpu 0 resume=path/to/trial/dir/ckpts/last.ckpt system.exporter_type=mesh-exporter system.geometry.isosurface_method=mc-cpu system.geometry.isosurface_resolution=256
```

不过直接导出基于NeRF表示的ckpt效果不会太好，你可以先参考threestudio里NeRF转mesh并refine的代码进行优化（比如这两个config, [geometry](https://github.com/threestudio-project/threestudio/blob/main/configs/prolificdreamer-geometry.yaml)和[texture](https://github.com/threestudio-project/threestudio/blob/main/configs/prolificdreamer-texture.yaml)），我可能要等这段时间忙完再把mesh refinement的代码整理进来。

**Comment by throb081** [comment]
谢谢您的答复！我近期又仔细看了一下您放上来的代码，发现代码一直在跑的是coarse阶段，是不是后面的细化阶段的代码是没有在发布的工程里面的呢，还是我得用别的指令去运行呢，

**Comment by HHLiufighting** [comment]
> 谢谢您的答复！ 我近期又仔细看了一下您放上来的代码，发现代码一直在跑的是coarse阶段，是不是后面的细化阶段的代码是没有在发布的工程里面的呢，还是我得用别的指令去运行呢，

是不是提供了obj的意思就是基于初始化的3D先验进行texture的优化呢，第一阶段获得3d先验的运行代码是哪一部分呢  不太理解，请问你搞明白了吗

**Comment by HHLiufighting** [comment]
> 感谢您的回复！！！对我帮助很大。我在Linux上成功运行了您的代码，并且生成的图片的效果真的很棒。然而我发现在changlog中提到可以将模型导出成obj文件，但是在生成的结果好像没有发现，想问一下如果想导出的结果为obj，需要进行一些什么设置呢

你好 我想请教一个问题  为什么我运行5000轮之后  就会out of memory呢 此前都是13G左右 ，请问你训练的时候会有这个情况吗
